features:
  price: 1
  price_log: 1
  price_vs_ma200: 1
  daily_return: 1
  gap_pct: 1
  weekly_return_5d: 1
  monthly_return_21d: 1
  quarterly_return_63d: 1
  ytd_return: 1
  dist_52w_high: 1
  dist_52w_low: 1
  pos_52w: 1
  sma20_ratio: 1
  sma50_ratio: 1
  sma200_ratio: 1
  sma20_sma50_ratio: 1
  sma50_sma200_ratio: 1
  sma50_slope: 1
  sma200_slope: 1
  volatility_5d: 1
  volatility_21d: 1
  volatility_ratio: 1
  atr14_normalized: 1
  log_volume: 1
  log_avg_volume_20d: 1
  relative_volume: 1
  rsi14: 1
  beta_spy_252d: 1
  candle_body_pct: 1
  candle_upper_wick_pct: 1
  candle_lower_wick_pct: 1
  higher_high_10d: 1
  higher_low_10d: 1
  swing_low_10d: 1
  trend_residual: 1
  macd_histogram_normalized: 1
  ppo_histogram: 1
  dpo: 1
  roc10: 1
  roc20: 1
  stochastic_k14: 1
  bollinger_band_width: 1
  adx14: 1
  chaikin_money_flow: 1
  donchian_position: 1
  donchian_breakout: 1
  ttm_squeeze_on: 1
  ttm_squeeze_momentum: 1
  obv_momentum: 1
  aroon_up: 1
  aroon_down: 1
  aroon_oscillator: 1
  cci20: 1
  williams_r14: 1
  kama_slope: 1
  fractal_dimension_index: 1
  hurst_exponent: 1
  price_curvature: 1
  volatility_of_volatility: 1
  mkt_spy_dist_sma200: 1
  mkt_spy_sma200_slope: 1
metadata:
  description: Removed normalization - Version 1
  feature_set: v2
  created_from: v1
