features:
  price: 0
  price_log: 0
  price_vs_ma200: 0
  close_position_in_range: 0
  log_return_1d: 0
  daily_return: 0
  gap_pct: 1
  weekly_return_5d: 0
  monthly_return_21d: 0
  quarterly_return_63d: 1
  ytd_return: 0
  weekly_return_1w: 0
  dist_52w_high: 1
  dist_52w_low: 1
  pos_52w: 0
  sma20_ratio: 0
  sma50_ratio: 0
  sma200_ratio: 0
  ema20_ratio: 0
  ema50_ratio: 0
  ema200_ratio: 0
  sma20_sma50_ratio: 0
  sma50_sma200_ratio: 1
  sma20_slope: 0
  sma50_slope: 0
  sma200_slope: 0
  ema20_slope: 0
  volatility_5d: 0
  volatility_21d: 1
  atr14_normalized: 1
  expansion_gap_ratio: 0
  log_volume: 0
  log_avg_volume_20d: 0
  relative_volume: 0
  obv_momentum: 0
  volume_trend: 0
  volume_momentum: 0
  rsi7: 0
  rsi14: 0
  rsi21: 0
  rsi_momentum: 0
  macd_line: 0
  macd_signal: 0
  macd_histogram_normalized: 0
  macd_momentum: 0
  roc5: 0
  roc10: 0
  roc20: 0
  momentum_10d: 0
  stochastic_k14: 0
  stochastic_d14: 0
  stochastic_oscillator: 0
  cci20: 0
  williams_r14: 0
  ppo_histogram: 0
  dpo: 0
  kama_slope: 0
  chaikin_money_flow: 0
  mfi: 0
  cmf_divergence: 1
  tsi: 0
  trend_residual: 0
  ultimate_oscillator: 0
  awesome_oscillator: 0
  momentum_20d: 0
  momentum_50d: 0
  momentum_divergence: 0
  momentum_consistency: 0
  momentum_acceleration: 0
  momentum_strength: 0
  momentum_persistence: 0
  momentum_exhaustion: 0
  momentum_reversal_signal: 0
  momentum_cross: 0
  momentum_rank: 0
  momentum_regime: 0
  momentum_5d: 0
  momentum_15d: 0
  momentum_30d: 0
  momentum_vs_price: 0
  volatility_regime: 0
  volatility_trend: 0
  bb_squeeze: 0
  bb_expansion: 0
  atr_ratio_20d: 0
  atr_ratio_252d: 1
  volatility_percentile_20d: 0
  volatility_percentile_252d: 0
  high_volatility_flag: 0
  low_volatility_flag: 0
  parkinson_volatility: 1
  garman_klass_volatility: 1
  rogers_satchell_volatility: 0
  yang_zhang_volatility: 0
  volatility_clustering: 0
  realized_volatility_5d: 0
  realized_volatility_20d: 1
  volatility_regime_change: 0
  adx14: 0
  adx20: 0
  adx50: 0
  trend_strength_20d: 0
  trend_strength_50d: 0
  ema_alignment: 0
  ma_crossover_bullish: 0
  ma_crossover_bearish: 0
  price_vs_all_mas: 0
  sma_slope_20d: 0
  sma_slope_50d: 0
  ema_slope_20d: 0
  ema_slope_50d: 0
  trend_consistency: 0
  trend_duration: 0
  trend_reversal_signal: 0
  trend_acceleration: 0
  trend_divergence: 0
  trend_pullback_strength: 0
  trend_breakout_strength: 0
  trend_following_strength: 0
  trend_regime: 0
  resistance_level_20d: 0
  resistance_level_50d: 0
  resistance_level_100d: 0
  support_level_20d: 0
  support_level_50d: 0
  support_level_100d: 1
  distance_to_resistance: 0
  distance_to_support: 0
  price_near_resistance: 0
  price_near_support: 0
  resistance_touches: 0
  support_touches: 0
  support_resistance_strength: 1
  donchian_position: 0
  pivot_point: 0
  pivot_resistance_1: 0
  pivot_support_1: 0
  fibonacci_retracement: 0
  volume_profile_poc: 0
  volume_profile_vah: 0
  volume_profile_val: 0
  price_vs_poc: 0
  price_vs_vah: 0
  price_vs_val: 0
  volume_weighted_price: 0
  price_vs_vwap: 0
  vwap_slope: 0
  vwap_distance_pct: 0
  volume_profile_width: 0
  volume_distribution: 0
  volume_climax: 0
  volume_dry_up: 0
  volume_breakout: 0
  volume_divergence: 0
  volume_autocorrelation: 1
  volume_imbalance: 1
  volume_directional_force: 1
  volume_at_price: 0
  volatility_ratio: 0
  weekly_return_2w: 0
  weekly_return_4w: 0
  weekly_volume_ratio: 0
  weekly_sma_5w: 0
  weekly_sma_10w: 0
  weekly_sma_20w: 0
  weekly_ema_5w: 0
  weekly_ema_10w: 0
  weekly_ema_20w: 0
  weekly_rsi_14w: 0
  weekly_rsi_7w: 0
  weekly_macd_histogram: 0
  weekly_macd_signal: 0
  weekly_adx: 0
  weekly_stochastic: 0
  close_vs_weekly_sma20: 0
  close_vs_weekly_ema20: 0
  weekly_atr_pct: 0
  weekly_trend_strength: 0
  weekly_momentum: 0
  monthly_return_1m: 0
  monthly_return_3m: 0
  monthly_sma_3m: 0
  monthly_sma_6m: 0
  monthly_rsi: 0
  candle_body_pct: 0
  candle_upper_wick_pct: 0
  candle_lower_wick_pct: 0
  candle_wicks_ratio: 0
  hanging_man: 0
  inverted_hammer: 0
  piercing_pattern: 0
  dark_cloud_cover: 0
  harami_bullish: 0
  harami_bearish: 0
  engulfing_bullish: 0
  engulfing_bearish: 0
  three_white_soldiers: 0
  three_black_crows: 0
  inside_bar: 0
  outside_bar: 0
  engulfing_strength: 0
  doji: 0
  hammer: 0
  shooting_star: 0
  marubozu: 0
  spinning_top: 0
  pattern_strength: 0
  pattern_confirmation: 0
  pattern_divergence: 0
  consecutive_green_days: 0
  consecutive_red_days: 0
  higher_high_10d: 0
  higher_low_10d: 0
  swing_low_10d: 1
  pattern_cluster: 0
  market_regime: 0
  regime_strength: 0
  regime_duration: 0
  regime_change_probability: 0
  trending_market_flag: 0
  choppy_market_flag: 0
  bull_market_flag: 0
  bear_market_flag: 0
  market_volatility_regime: 0
  market_momentum_regime: 0
  regime_transition: 0
  regime_stability: 0
  market_sentiment: 1
  market_fear_greed: 0
  regime_consistency: 0
  market_direction: 0
  market_direction_strength: 0
  market_trend_alignment: 0
  market_momentum: 0
  market_volatility_context: 0
  market_timing: 1
  market_support_resistance: 1
  market_regime_consistency: 0
  market_sector_rotation: 0
  market_breadth: 0
  market_leadership: 0
  market_sentiment_alignment: 0
  relative_strength_spy: 0
  relative_strength_spy_50d: 0
  rs_rank_20d: 0
  rs_rank_50d: 0
  rs_rank_100d: 0
  rs_momentum: 0
  outperformance_flag: 0
  rs_vs_price: 0
  rs_consistency: 0
  rs_regime: 0
  rs_trend: 0
  rs_acceleration: 1
  relative_strength_sector: 0
  day_of_week: 0
  day_of_week_sin: 0
  day_of_week_cos: 0
  day_of_month: 0
  day_of_month_sin: 0
  day_of_month_cos: 0
  month_of_year: 0
  month_of_year_sin: 1
  month_of_year_cos: 1
  quarter: 0
  is_month_end: 0
  is_quarter_end: 1
  is_year_end: 0
  trading_day_of_year: 1
  price_skewness_20d: 0
  price_kurtosis_20d: 0
  returns_skewness_20d: 0
  returns_kurtosis_20d: 1
  price_autocorrelation_1d: 0
  price_autocorrelation_5d: 0
  returns_autocorrelation: 0
  price_variance_ratio: 0
  price_half_life: 0
  returns_half_life: 0
  price_stationarity: 0
  returns_stationarity: 0
  price_cointegration: 0
  statistical_regime: 0
  volatility_skewness: 0
  volatility_kurtosis: 0
  volatility_autocorrelation: 0
  volatility_mean_reversion: 0
  volatility_of_volatility: 0
  volatility_regime_persistence: 0
  volatility_shock: 0
  volatility_normalized_returns: 0
  volatility_forecast: 1
  volatility_term_structure: 0
  volatility_risk_premium: 0
  volatility_smoothness: 0
  bollinger_band_width: 0
  fractal_dimension_index: 0
  hurst_exponent: 0
  price_curvature: 0
  aroon_up: 0
  aroon_down: 0
  aroon_oscillator: 0
  donchian_breakout: 0
  liquidity_measure: 0
  price_impact_proxy: 0
  bid_ask_spread_proxy: 0
  order_flow_imbalance: 0
  market_depth_proxy: 0
  price_efficiency: 0
  transaction_cost_proxy: 0
  market_quality: 0
  rsi_x_volume: 0
  rsi_x_atr: 0
  macd_x_volume: 0
  trend_x_momentum: 0
  volume_x_momentum: 0
  rsi_x_trend_strength: 0
  volatility_x_volume: 0
  volatility_x_trend: 0
  trend_x_volatility: 0
  volatility_x_regime_strength: 1
  price_position_x_rsi: 0
  support_resistance_x_momentum: 0
  rsi_x_support_distance: 0
  volume_x_breakout: 0
  momentum_x_regime: 0
  volume_x_regime: 0
  rsi_x_relative_strength: 0
  trend_x_relative_strength: 0
  momentum_x_time: 0
  volume_x_time: 0
  historical_gain_probability: 0
  gain_probability_score: 0
  gain_regime: 0
  gain_consistency: 0
  gain_timing: 0
  gain_momentum: 0
  gain_acceleration: 0
  target_distance: 0
  gain_momentum_strength: 1
  gain_breakout_signal: 0
  gain_risk_ratio: 0
  gain_volume_confirmation: 0
  gain_trend_alignment: 0
  gain_volatility_context: 0
  gain_support_level: 0
  signal_quality_score: 0
  signal_strength: 0
  signal_consistency: 0
  signal_confirmation: 0
  signal_timing: 0
  signal_risk_reward: 0
  signal_statistical_significance: 0
  signal_historical_success: 0
  signal_ensemble_score: 0
  false_positive_risk: 0
  signal_divergence: 0
  signal_volume_confirmation: 0
  signal_trend_alignment: 0
  signal_volatility_context: 0
  signal_regime_alignment: 1
  signal_momentum_strength: 0
  signal_support_resistance: 0
  signal_relative_strength: 0
  signal_multi_timeframe: 0
  signal_pattern_confirmation: 0
  mkt_spy_dist_sma200: 1
  mkt_spy_sma200_slope: 0
  beta_spy_252d: 1
  ttm_squeeze_on: 0
  ttm_squeeze_momentum: 0
  trend_consolidation: 0
  trend_exhaustion: 0
  trend_vs_mean_reversion: 0
  volatility_jump: 1
  volatility_forecast_accuracy: 1
  volatility_forecast_error: 0
  volatility_forecast_error_true: 0
  volatility_forecast_trend: 0
  volatility_clustering_strength: 0
  volatility_regime_forecast: 0
  volatility_surprise: 0
  volatility_realized_forecast_ratio: 0
  gain_probability_trend: 0
  gain_probability_consistency_rank: 0
  gain_probability_volatility_adjusted: 1
  dist_support_rank: 1
  volatility_rank: 1
  return_rank_3m: 0
  momentum_rank_trend: 0
  volatility_volume_correlation: 0
  volatility_volume_divergence: 0
  volatility_forecast_volume_confirmation: 0
  return_volatility_ratio: 0
  volatility_regime_transition_probability: 0
  gain_regime_transition_probability: 0
  momentum_regime_transition: 0
  top_features_ensemble: 1
  volatility_forecast_accuracy_weighted: 0
  gain_probability_volatility_regime_interaction: 0
  adr_percentage: 1
  monthly_vwap_slope: 0
  atr_channel_position: 0
  vpt_divergence: 0
  relative_strength_vs_sector: 0
  intraday_intensity: 0
  volume_climax_ratio: 0
  momentum_quality_r2: 0
  atr_expansion_ratio: 0
  relative_strength_momentum: 0
